import { JSZip } from './globals.js';
import { PRINT_MIME, refs, state } from './state.js';
import { blockBox, getPrintMatrix, meshTo3mfXml, prepareMeshData } from './geometry.js';
import { getInnerSlicePlaneZ } from './scene.js';

const CONTENT_TYPES = `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
  <Override PartName="/3D/3dmodel.model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
</Types>`;

const RELS = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>`;

function createSlic3rPrintConfig() {
    return `; generated by Crystal Slicer
;
; layer_height = 0.08
`;
}

function escapeXml(value) {
    return String(value)
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&apos;');
}

function createSlic3rObjectConfig(objectId, mesh, { name, extruder, fillDensity, fillPattern }) {
    const lastTriangleId = Math.max(0, mesh.triangles.length - 1);
    return ` <object id="${objectId}" instances_count="1">
  <metadata type="object" key="name" value="${escapeXml(name)}"/>
  <metadata type="object" key="extruder" value="${extruder}"/>
  <volume firstid="0" lastid="${lastTriangleId}">
   <metadata type="volume" key="name" value="${escapeXml(name)}"/>
   <metadata type="volume" key="volume_type" value="ModelPart"/>
   <metadata type="volume" key="extruder" value="${extruder}"/>
   <metadata type="volume" key="fill_density" value="${fillDensity}"/>
   <metadata type="volume" key="fill_pattern" value="${fillPattern}"/>
  </volume>
 </object>`;
}

function createSlic3rModelConfig({ blockMesh, innerMesh }) {
    return `<?xml version="1.0" encoding="UTF-8"?>
<config>
${createSlic3rObjectConfig(2, blockMesh, {
    name: 'Clear PLA Block',
    extruder: 1,
    fillDensity: '100%',
    fillPattern: 'alignedrectilinear'
})}
${createSlic3rObjectConfig(3, innerMesh, {
    name: 'Embedded Model',
    extruder: 2,
    fillDensity: '15%',
    fillPattern: 'rectilinear'
})}
</config>`;
}

export async function build3mfBlob(modelXml, options = {}) {
    const zip = new JSZip();
    zip.file('[Content_Types].xml', CONTENT_TYPES);
    zip.folder('_rels').file('.rels', RELS);
    zip.folder('3D').file('3dmodel.model', modelXml);
    if (options.includeSlicerSettings) {
        const metadata = zip.folder('Metadata');
        metadata.file('Slic3r_PE.config', createSlic3rPrintConfig());
        metadata.file('Slic3r_PE_model.config', createSlic3rModelConfig(options.slic3rModelConfig));
    }
    const bytes = await zip.generateAsync({
        type: 'uint8array',
        compression: 'DEFLATE',
        compressionOptions: { level: 6 }
    });
    return new Blob([bytes], { type: PRINT_MIME });
}

function wrapModel(title, resourcesXml, buildXml) {
    return `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <metadata name="Application">Clear Print Tools Crystal Slicer</metadata>
  <metadata name="slic3rpe:Version3mf">1</metadata>
  <metadata name="Title">${title}</metadata>
  <resources>
${resourcesXml}
  </resources>
  <build>
${buildXml}
  </build>
</model>
`;
}

export async function buildCrystalModelXml() {
    if (!refs.crystalBlock || !refs.innerModelGroup) {
        throw new Error('Scene is not ready');
    }
    const printMatrix = getPrintMatrix(state.blockD);
    const clipBox = blockBox(state, 0.02);
    if (state.sliceHalfCenter) {
        const centerSliceZ = getInnerSlicePlaneZ();
        if (centerSliceZ !== null) {
            clipBox.min.z = Math.max(clipBox.min.z, centerSliceZ);
        }
    }

    const blockMesh = await prepareMeshData(refs.crystalBlock, { printMatrix });
    const innerMesh = await prepareMeshData(refs.innerModelGroup, { printMatrix, clipBox });

    if (!blockMesh.triangles.length) throw new Error('Crystal block mesh is empty');
    if (!innerMesh.triangles.length) {
        throw new Error('Embedded model is empty or fully outside the block. Reposition it and try again.');
    }

    const resources = `    <basematerials id="1">
      <base name="Clear PLA" displaycolor="#E2E8F0FF"/>
      <base name="Solid Color PLA" displaycolor="#2563EBFF"/>
    </basematerials>
    <object id="2" name="Clear PLA Block" type="model" pid="1" pindex="0">
${meshTo3mfXml(blockMesh.vertices, blockMesh.triangles)}
    </object>
    <object id="3" name="Embedded Model" type="model" pid="1" pindex="1">
${meshTo3mfXml(innerMesh.vertices, innerMesh.triangles)}
    </object>
    <object id="4" name="Crystal Assembly" type="model">
      <components>
        <component objectid="2"/>
        <component objectid="3"/>
      </components>
    </object>`;

    return {
        xml: wrapModel('Crystal Block Assembly', resources, '    <item objectid="4"/>'),
        blockMesh,
        innerMesh
    };
}

export async function exportCrystal3MF() {
    const { xml, blockMesh, innerMesh } = await buildCrystalModelXml();
    const blob = await build3mfBlob(xml, {
        includeSlicerSettings: true,
        slic3rModelConfig: { blockMesh, innerMesh }
    });
    return { blob, xml, blockMesh, innerMesh };
}
